import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Docusaurus generates the sidebar from the docs/ folder structure — numeric
// filename/foldername prefixes control ordering and are stripped from labels/slugs.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
